"""
SMTP Email Configuration
Generates msmtprc config and writes it into the Asterisk container
"""

import logging
import subprocess

logger = logging.getLogger(__name__)


def generate_msmtp_config(settings: dict) -> str:
    """Generate msmtprc configuration content"""
    host = settings.get("smtp_host", "")
    port = settings.get("smtp_port", "587")
    tls = settings.get("smtp_tls", "true")
    user = settings.get("smtp_user", "")
    password = settings.get("smtp_password", "")
    from_addr = settings.get("smtp_from", "")

    tls_on = "on" if tls.lower() in ("true", "1", "on", "yes") else "off"

    config = f"""# Auto-generated by GonoPBX
defaults
auth           on
tls            {tls_on}
tls_trust_file /etc/ssl/certs/ca-certificates.crt
logfile        /var/log/msmtp.log

account        default
host           {host}
port           {port}
from           {from_addr}
user           {user}
password       {password}
"""
    return config


def write_msmtp_config(settings: dict) -> bool:
    """Write msmtp config into the Asterisk container"""
    try:
        config_content = generate_msmtp_config(settings)
        result = subprocess.run(
            ['docker', 'exec', '-i', 'pbx_asterisk', 'sh', '-c',
             'cat > /etc/msmtprc && chmod 600 /etc/msmtprc'],
            input=config_content,
            capture_output=True,
            text=True,
            timeout=10
        )
        if result.returncode == 0:
            logger.info("msmtp config written to Asterisk container")
            return True
        else:
            logger.error(f"Failed to write msmtp config: {result.stderr}")
            return False
    except Exception as e:
        logger.error(f"Failed to write msmtp config: {e}")
        return False


def send_test_email(settings: dict, to_address: str) -> bool:
    """Send a test email via the Asterisk container"""
    from_addr = settings.get("smtp_from", "voicemail@gonopbx.local")
    subject = "GonoPBX Test-E-Mail"
    body = "Dies ist eine Test-E-Mail von GonoPBX. Die SMTP-Konfiguration funktioniert."

    mail_content = f"To: {to_address}\nFrom: {from_addr}\nSubject: {subject}\n\n{body}\n"

    try:
        result = subprocess.run(
            ['docker', 'exec', '-i', 'pbx_asterisk', 'msmtp', '-t'],
            input=mail_content,
            capture_output=True,
            text=True,
            timeout=30
        )
        if result.returncode == 0:
            logger.info(f"Test email sent to {to_address}")
            return True
        else:
            logger.error(f"Test email failed: {result.stderr}")
            return False
    except Exception as e:
        logger.error(f"Failed to send test email: {e}")
        return False
