"""
Queue (queues.conf) Generator for Ring Groups
"""
import os
import logging
import subprocess
from typing import List
from database import RingGroup

logger = logging.getLogger(__name__)

QUEUE_CONFIG_PATH = "/etc/asterisk/custom/queues.conf"

STRATEGY_MAP = {
    "ringall": "ringall",
    "roundrobin": "rrmemory",
    "leastrecent": "leastrecent",
}


def generate_queues_config(groups: List[RingGroup]) -> str:
    """Generate queues.conf for ring groups"""
    config = """; Auto-generated Queue configuration
; Generated by Asterisk PBX GUI

[general]
; keep empty - defaults apply

"""

    for group in sorted(groups, key=lambda g: g.extension):
        if not group.enabled:
            continue
        queue_name = f"rg_{group.id}"
        strategy = STRATEGY_MAP.get(group.strategy or "ringall", "ringall")
        ring_time = group.ring_time or 20
        config += f"[{queue_name}]\n"
        config += f"strategy={strategy}\n"
        config += f"timeout={ring_time}\n"
        config += "retry=1\n"
        config += "wrapuptime=0\n"
        config += "maxlen=0\n"
        config += "joinempty=yes\n"
        config += "leavewhenempty=no\n"
        config += "ringinuse=yes\n"
        # Members
        for member in sorted(group.members, key=lambda m: m.position):
            config += f"member => PJSIP/{member.extension}\n"
        config += "\n"

    return config


def write_queues_config(groups: List[RingGroup]) -> bool:
    """Write queues.conf to shared volume"""
    try:
        content = generate_queues_config(groups)
        os.makedirs(os.path.dirname(QUEUE_CONFIG_PATH), exist_ok=True)
        with open(QUEUE_CONFIG_PATH, "w") as f:
            f.write(content)
        logger.info(f"queues.conf written with {len(groups)} ring groups")
        return True
    except Exception as e:
        logger.error(f"Failed to write queues.conf: {e}")
        return False


def reload_queues() -> bool:
    """Reload Asterisk queues"""
    try:
        result = subprocess.run(
            [
                "docker",
                "exec",
                "pbx_asterisk",
                "sh",
                "-c",
                "cp /etc/asterisk/custom/queues.conf /etc/asterisk/queues.conf && asterisk -rx \"queue reload all\"",
            ],
            capture_output=True,
            text=True,
            timeout=10,
        )
        if result.returncode == 0:
            logger.info("Asterisk queues reloaded successfully")
            return True
        logger.error(f"Queue reload failed: {result.stderr}")
        return False
    except Exception as e:
        logger.error(f"Failed to reload queues: {e}")
        return False
