"""
Voicemail Configuration Generator
"""
import os
import logging
import subprocess
from typing import List, Optional

from database import VoicemailMailbox

logger = logging.getLogger(__name__)

VOICEMAIL_CONFIG_PATH = "/etc/asterisk/custom/voicemail.conf"


def generate_voicemail_config(mailboxes: List[VoicemailMailbox], smtp_settings: Optional[dict] = None) -> str:
    """Generate complete voicemail.conf content"""

    smtp_from = "voicemail@gonopbx.local"
    mailcmd = ""

    if smtp_settings and smtp_settings.get("smtp_host"):
        smtp_from = smtp_settings.get("smtp_from", smtp_from)
        mailcmd = "\nmailcmd=/usr/bin/msmtp -t"

    config = f"""; Auto-generated Voicemail configuration
; Generated by GonoPBX

[general]
format=wav49|wav
serveremail={smtp_from}
attach=yes{mailcmd}
skipms=3000
maxsilence=10
silencethreshold=128
maxlogins=3
maxmsg=100
maxsecs=300
minsecs=3
maxgreet=60
review=yes
saycid=yes
envelope=yes
operator=no
delete=no
nextaftercmd=yes
forcename=no
forcegreetings=no
emailsubject=Neue Voicemail von ${{VM_CALLERID}} (Dauer: ${{VM_DUR}})
emailbody=Hallo ${{VM_NAME}},\\n\\nSie haben eine neue Voicemail-Nachricht:\\n\\nVon: ${{VM_CALLERID}}\\nDatum: ${{VM_DATE}}\\nDauer: ${{VM_DUR}}\\nMailbox: ${{VM_MAILBOX}}\\n\\nDie Nachricht ist als Anhang beigefuegt.\\n\\nMit freundlichen Gruessen\\nIhre GonoPBX Telefonanlage

[zonemessages]
european=Europe/Berlin|'vm-received' Q 'digits/at' IMp

[default]
"""

    for mb in mailboxes:
        if mb.enabled:
            email_part = f",{mb.email}" if mb.email else ""
            name = mb.name or mb.extension
            config += f"{mb.extension} => {mb.pin},{name}{email_part}\n"

    return config


def write_voicemail_config(mailboxes: List[VoicemailMailbox], smtp_settings: Optional[dict] = None) -> bool:
    """Write voicemail config to file"""
    try:
        config_content = generate_voicemail_config(mailboxes, smtp_settings)

        os.makedirs(os.path.dirname(VOICEMAIL_CONFIG_PATH), exist_ok=True)

        with open(VOICEMAIL_CONFIG_PATH, 'w') as f:
            f.write(config_content)

        logger.info(f"Voicemail config written with {len(mailboxes)} mailboxes")
        return True

    except Exception as e:
        logger.error(f"Failed to write voicemail config: {e}")
        return False


def reload_voicemail() -> bool:
    """Reload Asterisk voicemail - copy config inside Asterisk container"""
    try:
        result = subprocess.run(
            ['docker', 'exec', 'pbx_asterisk', 'sh', '-c',
             'cp /etc/asterisk/custom/voicemail.conf /etc/asterisk/voicemail.conf && asterisk -rx "voicemail reload"'],
            capture_output=True,
            text=True,
            timeout=10
        )

        if result.returncode == 0:
            logger.info("Asterisk voicemail reloaded successfully")
            return True
        else:
            logger.error(f"Voicemail reload failed: {result.stderr}")
            return False

    except Exception as e:
        logger.error(f"Failed to reload voicemail: {e}")
        return False
